#!/bin/sh
data="$(mktemp -d /tmp/chtmp-XXXXXX)"
cache="$(mktemp -d /tmp/chtmp-XXXXXX)"

apps="Manganese Chromium Chrome"
for app in $apps; do
  open -a "$app"  --args \
    --user-data-dir="$data" --disk-cache-dir="$cache" 2>/dev/null && exit
done
